"""Initial WIP models migration

Revision ID: 6856b39e3965
Revises: 
Create Date: 2025-08-16 06:45:25.044278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6856b39e3965'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_contract_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_job_number'), 'projects', ['job_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wip_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('column_position', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('is_calculated', sa.String(length=10), nullable=True),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_record_id'), 'audit_log', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('wip_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('job_number', sa.String(length=20), nullable=True),
    sa.Column('current_month_original_contract_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month original contract amount'),
    sa.Column('current_month_change_order_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month change order amount'),
    sa.Column('current_month_total_contract_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month total contract amount'),
    sa.Column('prior_month_total_contract_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Prior month total contract amount'),
    sa.Column('current_vs_prior_contract_variance', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month vs prior month contract variance'),
    sa.Column('current_month_cost_to_date', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month cost to date'),
    sa.Column('current_month_estimated_cost_to_complete', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month estimated cost to complete'),
    sa.Column('current_month_estimated_final_cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month estimated final cost'),
    sa.Column('prior_month_estimated_final_cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='Prior month estimated final cost'),
    sa.Column('current_vs_prior_estimated_final_cost_variance', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current vs prior month estimated final cost variance'),
    sa.Column('us_gaap_percent_completion', sa.Numeric(precision=5, scale=2), nullable=True, comment='US GAAP % of Completion'),
    sa.Column('revenue_earned_to_date_us_gaap', sa.Numeric(precision=15, scale=2), nullable=True, comment='Revenue Earned to Date US GAAP % of Completion'),
    sa.Column('estimated_job_margin_to_date_us_gaap', sa.Numeric(precision=15, scale=2), nullable=True, comment='Estimated Job Margin to Date Using US GAAP % of Completion'),
    sa.Column('estimated_job_margin_to_date_percent_sales', sa.Numeric(precision=5, scale=2), nullable=True, comment='Estimated Job Margin to Date as a % of Sales'),
    sa.Column('current_month_estimated_job_margin_at_completion', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month estimated job margin at completion'),
    sa.Column('prior_month_estimated_job_margin_at_completion', sa.Numeric(precision=15, scale=2), nullable=True, comment='Prior month estimated job margin at completion'),
    sa.Column('current_vs_prior_estimated_job_margin', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current vs prior month estimated job margin variance'),
    sa.Column('current_month_estimated_job_margin_percent_sales', sa.Numeric(precision=5, scale=2), nullable=True, comment='Current month estimated job margin as % of sales'),
    sa.Column('current_month_revenue_billed_to_date', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month revenue billed to date'),
    sa.Column('current_month_costs_in_excess_billings', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month costs in excess of billings'),
    sa.Column('current_month_billings_excess_revenue', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month billings in excess of revenue'),
    sa.Column('current_month_addl_entry_required', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month additional entry required'),
    sa.Column('billed_to_date', sa.Numeric(precision=15, scale=2), nullable=True, comment='Current month billed to date'),
    sa.Column('costs_in_excess_of_billings', sa.Numeric(precision=15, scale=2), nullable=True, comment='Costs in Excess of Billings'),
    sa.Column('billings_in_excess_of_costs', sa.Numeric(precision=15, scale=2), nullable=True, comment='Billings in Excess of Costs'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'report_date', name='uq_project_report_date')
    )
    op.create_index(op.f('ix_wip_snapshots_id'), 'wip_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_wip_snapshots_job_number'), 'wip_snapshots', ['job_number'], unique=False)
    op.create_index(op.f('ix_wip_snapshots_report_date'), 'wip_snapshots', ['report_date'], unique=False)
    op.create_table('cell_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wip_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wip_snapshot_id'], ['wip_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cell_explanations_field_name'), 'cell_explanations', ['field_name'], unique=False)
    op.create_index(op.f('ix_cell_explanations_id'), 'cell_explanations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_explanations_id'), table_name='cell_explanations')
    op.drop_index(op.f('ix_cell_explanations_field_name'), table_name='cell_explanations')
    op.drop_table('cell_explanations')
    op.drop_index(op.f('ix_wip_snapshots_report_date'), table_name='wip_snapshots')
    op.drop_index(op.f('ix_wip_snapshots_job_number'), table_name='wip_snapshots')
    op.drop_index(op.f('ix_wip_snapshots_id'), table_name='wip_snapshots')
    op.drop_table('wip_snapshots')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_record_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('wip_field_definitions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_job_number'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
